[tool.poetry]
name = "gigaku"
version = "0.1.0"
description = "Migaku extension automation script"
package-mode = false

[tool.poetry.dependencies]
python = "^3.14"
playwright = "^1.40.0"
selenium = "^4.40.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
